name: Validate meta data

on:
  pull_request:
    branches: [main]
    paths:
      - "meta.yaml"
  push:
    branches: [main]
    paths:
      - "meta.yaml"

permissions:
  contents: read

jobs:
  validate-meta-data:
    runs-on: ubuntu-latest
    name: Validate meta data file
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: mikefarah/yq@2be0094729a1006f61e8339ce9934bfb3cbb549f # v4.52.2
        with:
          cmd: yq -o=json '.' meta.yaml > meta.json
      - name: Validate meta data
        uses: cardinalby/schema-validator-action@2166123eb256fa40baef7e22ab1379708425efc7 # v3
        with:
          file: meta.json
          schema: meta.schema.json
