name: Validate meta data

on:
  pull_request:
    branches: [main]
    paths:
      - "meta.yaml"
  push:
    branches: [main]
    paths:
      - "meta.yaml"

permissions:
  contents: read

jobs:
  validate-meta-data:
    runs-on: ubuntu-latest
    name: Validate meta data file
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: mikefarah/yq@065b200af9851db0d5132f50bc10b1406ea5c0a8 # v4.50.1
        with:
          cmd: yq -o=json '.' meta.yaml > meta.json
      - name: Validate meta data
        uses: cardinalby/schema-validator-action@2166123eb256fa40baef7e22ab1379708425efc7 # v3
        with:
          file: meta.json
          schema: meta.schema.json
